### PR TITLE
Use metalink instead of mirrorlist

### PR DESCRIPTION
**Pull request by oguya**
Metalinks[1] prevent yum & dnf from using stale and or malicious mirrors. Fedora 20 & above now ship with metalink instead of mirrorlist.

1. https://fedoraproject.org/wiki/Features/YumMetalinks

### CODE REVIEW

**Comment by alanorth** [comment]
... but we're not using the metalinks anyways. We override the baseurl. ;)

**Comment by oguya** [comment]
I just added as a BTW. Just in case, you're in Kenya, you can use our beloved [mjanja mirror](mirror.mjanja.co.ke), but when you go to another country with super fast net, you can switch back from `baseurl` to `metalink`.

**Comment by alanorth** [comment]
Ok, maybe a better rationale for the pull request would be to update to a newer Fedora repo file.

**Comment by oguya** [comment]
Totally makes sense, considering there are a few `dnf` related additions in the Fedora repo file.

**Pull request closed without merging**
